source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/tradingticket/SpecRepo'

target 'SwiftExampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'TradeItAccountOpeningSDK', "~> 1.2.8"
end

target 'ObjCExampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'TradeItAccountOpeningSDK', "~> 1.2.8"
end


